### ISSUE TITLE
cloud_say TTS platform not working

### ISSUE THREAD

**Issue by Stuke00** [nimroddolev/chime_tts#13]
## System Information

version | core-2023.8.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.39
arch | x86_64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4809
Installed Version | 1.32.1
Stage | running
Available Repositories | 1269
Downloaded Repositories | 15

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | September 14, 2023 at 7:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | us-east-1-4.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 234.0 GB
disk_used | 8.7 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.2), eufy-security-ws (1.6.2), PS5 MQTT (1.3.1), Terminal & SSH (9.7.1), Tailscale (0.11.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 5
views | 24
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 26, 2023 at 1:57 PM
-- | --
current_recorder_run | August 18, 2023 at 6:52 AM
estimated_db_size | 3457.08 MiB
database_engine | mysql
database_version | 10.11.5

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When using cloud_say as a TTS platform, I get the error below.  The chime plays, just no message TTS.  The build in TTS service for cloud_say works just fine on its own.  

    "tts_platform": "cloud_say",
    "message": "Testing.",
    "chime_path": "custom_components/chime_tts/mp3s/mario_coin.mp3"

### Reproduction steps

1. Call service with above data parameters
2.
3.
...

### Debug logs

```text
2023-08-18 07:03:55.784 WARNING (MainThread) [custom_components.chime_tts] - Error calling tts.media_source.generate_media_source_id: Invalid TTS provider selected
2023-08-18 07:03:55.785 WARNING (MainThread) [custom_components.chime_tts] Unable to generate TTS audio
2023-08-18 07:04:05.245 WARNING (MainThread) [custom_components.chime_tts] - Error calling tts.media_source.generate_media_source_id: Invalid TTS provider selected
2023-08-18 07:04:05.248 WARNING (MainThread) [custom_components.chime_tts] Unable to generate TTS audio
2023-08-18 07:04:46.792 WARNING (MainThread) [custom_components.chime_tts] - Error calling tts.media_source.generate_media_source_id: Invalid TTS provider selected
2023-08-18 07:04:46.794 WARNING (MainThread) [custom_components.chime_tts] Unable to generate TTS audio
2023-08-18 07:08:16.185 WARNING (MainThread) [custom_components.chime_tts] - Error calling tts.media_source.generate_media_source_id: Invalid TTS provider selected
2023-08-18 07:08:16.187 WARNING (MainThread) [custom_components.chime_tts] Unable to generate TTS audio
```

**Comment by nimroddolev** [comment]
The issue has been fixed in v0.7.2

**Comment by Stuke00** [comment]
I installed 0.7.2 and still getting the same error.  

2023-08-20 19:08:35.435 WARNING (MainThread) [custom_components.chime_tts] - Error calling tts.media_source.generate_media_source_id: Invalid TTS provider selected
2023-08-20 19:08:35.445 WARNING (MainThread) [custom_components.chime_tts] Unable to generate TTS audio

**Comment by nimroddolev** [comment]
The fix involved changing the `tts_platform` value from `cloud_say` to `cloud`.
Can you please check that you are calling the service with this updated value?
